"""empty message

Revision ID: 916fc45fbb4d
Revises: a5fd1b3e163b
Create Date: 2021-10-31 00:00:09.902759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916fc45fbb4d'
down_revision = 'a5fd1b3e163b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_table', sa.Column('sql_con', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_table', 'sql_con')
    # ### end Alembic commands ###
