"""empty message

Revision ID: a5fd1b3e163b
Revises: f15a5c3e2b65
Create Date: 2021-10-27 22:39:09.345718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fd1b3e163b'
down_revision = 'f15a5c3e2b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_table', sa.Column('creation_time', sa.Time(), nullable=True))
    op.add_column('query_table', sa.Column('last_creation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_table', 'last_creation')
    op.drop_column('query_table', 'creation_time')
    # ### end Alembic commands ###
